apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agesport-postgres-data
  namespace: agesport
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agesport-uploads
  namespace: agesport
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agesport-backups
  namespace: agesport
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 5Gi
